name: 提交刷新

on: workflow_dispatch

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: date > .timestamp && git add . && git commit -m "刷新" && git push || echo "无更改"